# Generated by Django 3.2.7 on 2021-09-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memoir',
            table='Memoir',
        ),
    ]
